# Set global configuration.
export EDITOR='vim'
export PATH='/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin'
export TERM='xterm-256color'
export ZSH=~/.oh-my-zsh

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS=true

# Use hyphen-insensitive completion. _ and - will be interchangeable.
HYPHEN_INSENSITIVE=true

# Append history rather than replace it.
setopt APPEND_HISTORY

# Do not add duplicates of the previous command to the history.
setopt HIST_IGNORE_DUPS

# Do not add commands starting with a space character to the history.
setopt HIST_IGNORE_SPACE

# Do not throw any error if a pattern for filename generation has no matches.
unsetopt NOMATCH

# Set name and parameters of the theme to load.
ZSH_THEME='bullet-train'
BULLETTRAIN_TIME_SHOW=true
BULLETTRAIN_TIME_BG=241
BULLETTRAIN_TIME_FG=black
BULLETTRAIN_STATUS_SHOW=true
BULLETTRAIN_RVM_SHOW=false
BULLETTRAIN_VIRTUALENV_SHOW=true
BULLETTRAIN_NVM_SHOW=false
BULLETTRAIN_CONTEXT_SHOW=true
BULLETTRAIN_CONTEXT_BG=yellow
BULLETTRAIN_CONTEXT_FG=black
BULLETTRAIN_DIR_SHOW=true
BULLETTRAIN_GIT_SHOW=true
BULLETTRAIN_HG_SHOW=true

# Set plugins to load.
plugins=(
  common-aliases  # aliases for common Unix utilities
  copyfile  # copy file to system-wide clipboard
  osx  # access OS X applications from terminal
  python  # pyfind, pyclean, pygrep
)

# Load oh-my-zsh.
source $ZSH/oh-my-zsh.sh

# Set solarized colors for the GNU ls utility and for zsh completion.
case "$OSTYPE" in
  darwin*)
    eval `gdircolors ~/.dircolors.ansi-dark`
    ;;
  linux*)
    eval `dircolors ~/.dircolors.ansi-dark`
    ;;
esac
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# Set additional aliases.
case "$OSTYPE" in
  darwin*)
    alias ls='gls -F --color=auto'
    ;;
  linux*)
    alias ls='ls -F --color=auto'
    ;;
esac
alias ws='cd ~/workspace'

# Map various keys to custom functionality.
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
zmodload zsh/terminfo
bindkey "$terminfo[kent]" accept-line  # keypad Enter
bindkey "$terminfo[kcuu1]" history-beginning-search-backward-end  # UP arrow
bindkey "$terminfo[kcud1]" history-beginning-search-forward-end   # DOWN arrow

# Start ``screen`` automatically when coming from a remote SSH connection. Try
# it only once, to avoid looping in case ``screen`` fails for some reason.
if [ -n "$SSH_TTY" -a -z "$STARTED_SCREEN" ]
then
  export STARTED_SCREEN=1
  screen -RR
fi

# Enable local settings, which override general settings.
if [ -f ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi
