# Set global configuration.
export EDITOR='vim'
export PATH='/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin'
export TERM='xterm-256color'
export ZSH=~/.oh-my-zsh

# Map numpad keys to their equivalents.
# 0 . Enter
bindkey -s "^[Op" "0"
bindkey -s "^[Ol" "."
bindkey -s "^[OM" "^M"
# 1 2 3
bindkey -s "^[Oq" "1"
bindkey -s "^[Or" "2"
bindkey -s "^[Os" "3"
# 4 5 6
bindkey -s "^[Ot" "4"
bindkey -s "^[Ou" "5"
bindkey -s "^[Ov" "6"
# 7 8 9
bindkey -s "^[Ow" "7"
bindkey -s "^[Ox" "8"
bindkey -s "^[Oy" "9"
# + -  * /
bindkey -s "^[Ok" "+"
bindkey -s "^[Om" "-"
bindkey -s "^[Oj" "*"
bindkey -s "^[Oo" "/"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS=true

# Use hyphen-insensitive completion. _ and - will be interchangeable.
HYPHEN_INSENSITIVE=true

# Enable command auto-correction.
ENABLE_CORRECTION=true

# Append history rather than replace it.
setopt APPEND_HISTORY

# Do not add duplicates of the previous command to the history.
setopt HIST_IGNORE_DUPS

# Do not add commands starting with a space character to the history.
setopt HIST_IGNORE_SPACE

# Set name and parameters of the theme to load.
ZSH_THEME='bullet-train'
BULLETTRAIN_TIME_SHOW=true
BULLETTRAIN_STATUS_SHOW=true
BULLETTRAIN_RVM_SHOW=false
BULLETTRAIN_VIRTUALENV_SHOW=true
BULLETTRAIN_NVM_SHOW=false
BULLETTRAIN_CONTEXT_SHOW=false
BULLETTRAIN_DIR_SHOW=true
BULLETTRAIN_GIT_SHOW=true

# Set plugins to load.
plugins=(
  common-aliases  # aliases for common Unix utilities
  copyfile  # copy file to system-wide clipboard
  osx  # access OS X applications from terminal
  python  # pyfind, pyclean, pygrep
)

# Load oh-my-zsh.
source $ZSH/oh-my-zsh.sh

# Set solarized colors for the GNU ls utility and for zsh completion.
case "$OSTYPE" in
  darwin*)
    eval `gdircolors ~/.dircolors.ansi-dark`
    ;;
  linux*)
    eval `dircolors ~/.dircolors.ansi-dark`
    ;;
esac
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# Set additional aliases.
case "$OSTYPE" in
  darwin*)
    alias ls='gls -F --color=auto'
    ;;
  linux*)
    alias ls='ls -F --color=auto'
    ;;
esac
alias ws='cd ~/workspace'

# Enable local settings, which override general settings.
if [ -f ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi
