# Paths. {{{
PATH=/usr/bin:/bin:/usr/sbin:/sbin
PATH=/usr/local/bin:${PATH}  # Local binaries override system binaries.
export PATH
# }}}

# Aliases. {{{
shopt -s expand_aliases
case "$OSTYPE" in
  darwin*)
    # 'gls' and 'gdircolors' are available from the 'coreutils' package
    # installed via 'port'.
    alias ls='gls -F --color=auto'
    eval `gdircolors ~/.dircolors.ansi-dark`
    ;;
  linux*)
    alias ls='ls -F --color=auto'
    eval `dircolors ~/.dircolors.ansi-dark`
    ;;
esac
alias ll='ls -l'
alias la='ls -lA'

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

alias ps='ps -f'

alias ws='cd ~/workspace'
# }}}

# History. {{{
export PROMPT_COMMAND="history -a"  # Save command history.
export HISTCONTROL=ignoreboth  # No duplicates or lines starting with space.
export HISTFILESIZE=1073741824
export HISTSIZE=1048576
shopt -s histappend  # Append to the history file, don't overwrite it.
bind '"\e[A":history-search-backward' 2>/dev/null  # Backward history search.
bind '"\e[B":history-search-forward' 2>/dev/null  # Forward history search.
# }}}

# Bash completion. {{{
case "$OSTYPE" in
  darwin*)
    if [ -f $(brew --prefix)/etc/bash_completion ]; then
      . $(brew --prefix)/etc/bash_completion
    fi
    ;;
  linux*)
    if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
      . /etc/bash_completion
    fi
    ;;
esac
# }}}

# Visual. {{{
# Update the values of LINES and COLUMNS after the window size has changed.
shopt -s checkwinsize

# Gnome Terminal colors.
case "$OSTYPE" in
  linux*)
    source ~/.gnome-terminal-solarize.sh dark
    ;;
esac

# Powerline.
if [ -f ~/.vim/bundle/powerline/powerline/bindings/bash/powerline.sh ]; then
  source ~/.vim/bundle/powerline/powerline/bindings/bash/powerline.sh
fi
# }}}

# Local settings to override general settings. {{{
if [ -f ~/.bashrc.local ]; then
  source ~/.bashrc.local
fi
# }}}
